name: first-interaction

on:
  issues:
    types: [opened]
  pull_request:
    branches: [main]
    types: [opened]

jobs:
  check_for_first_interaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/first-interaction@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello! Thank you for filing an issue.

            Please make sure you had used one of our issue templates unless their was no templates for your issue. If there is a template for your issue and you had not used it, please close the issue and recreate it using the template and filling out all the feilds that apply. If you fail to do sure without being on the endeavorjs team, the ticket will be closed. 
          pr-message: |
            Hello! Thank you for your contribution.
            
            If you are fixing a bug, please reference the issue number in the description.

            If you are implementing anything else please link the issue number in the description please.
            
            Make sure you are following the PR template.
